"""update

Revision ID: 1e37eee31516
Revises: d935033cb954
Create Date: 2025-02-21 21:17:57.537600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e37eee31516'
down_revision = 'd935033cb954'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_free_trial_ad_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_used_free_trial', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('used_free_trial_ad_accounts', schema=None) as batch_op:
        batch_op.drop_column('has_used_free_trial')

    # ### end Alembic commands ###
