"""Added support for multiple customer IDs

Revision ID: 3554e4fbc8ab
Revises: 9df4cccd0fd2
Create Date: 2025-02-18 06:09:27.534413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3554e4fbc8ab'
down_revision = '9df4cccd0fd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_ids', sa.Text(), nullable=True))
        batch_op.drop_constraint('user_stripe_customer_id_key', type_='unique')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('user_stripe_customer_id_key', ['stripe_customer_id'])
        batch_op.drop_column('stripe_customer_ids')

    # ### end Alembic commands ###
