"""Added is_active_manual field to AdAccount

Revision ID: 612e2260f230
Revises: 6dbfc68f562a
Create Date: 2025-02-19 00:20:18.009884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '612e2260f230'
down_revision = '6dbfc68f562a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active_manual', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ad_account', schema=None) as batch_op:
        batch_op.drop_column('is_active_manual')

    # ### end Alembic commands ###
