"""Added support for multiple customer IDs

Revision ID: 6dbfc68f562a
Revises: 3554e4fbc8ab
Create Date: 2025-02-18 07:37:57.333959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbfc68f562a'
down_revision = '3554e4fbc8ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_id', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['stripe_customer_id'])
        batch_op.drop_column('stripe_customer_ids')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_customer_ids', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('stripe_customer_id')

    # ### end Alembic commands ###
