"""active ad account

Revision ID: 87e00028b5d5
Revises: 612e2260f230
Create Date: 2025-02-21 10:04:30.358235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87e00028b5d5'
down_revision = '612e2260f230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active_ad_account', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('active_ad_account')

    # ### end Alembic commands ###
