"""update

Revision ID: d935033cb954
Revises: 87e00028b5d5
Create Date: 2025-02-21 21:16:00.400903

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd935033cb954'
down_revision = '87e00028b5d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('used_free_trial_ad_accounts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_free_trial_ad_accounts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ad_account_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('has_used_free_trial', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='used_free_trial_ad_accounts_pkey'),
    sa.UniqueConstraint('ad_account_id', name='used_free_trial_ad_accounts_ad_account_id_key')
    )
    # ### end Alembic commands ###
